#!/bin/bash
# sandboxp/scripts/clean
#
# cleans out previous build and install files
# does not clean out any log files in sandboxp/logs
#
# cleans out any CMake files mistakenly created by
# running cmake in the wrong directory
#
function _printLog(){
  # Possible special case for the terminal: echo "${PROGNAME}: $@"
  # That would be more precise but rather verbose, and not all output uses
  # _printLog() for now, so it would look too inconsistent.
  echo "$@" | tee -a "$LOGFILE"
}

function _doLog(){
  # Possible special case for the terminal: echo "${PROGNAME}: $@"
  # That would be more precise but rather verbose, and not all output uses
  # _printLog() for now, so it would look too inconsistent.
  echo "$@" | tee -a "$LOGFILE"
  $@  2>&1 | tee -a "$LOGFILE"
}
# Echo the contents of stdin to the terminal and/or to $LOGFILE.

SCRIPT_NAME=$(basename "$0")
SCRIPTS_DIR=$(pwd)
cd $(dirname "$0")
SCRIPTS_DIR=$(pwd)
cd ../
SANDBOXP_DIR=$(pwd)
INSTALL_DIR_SANDBOXP=$SANDBOXP_DIR/install
LOGFILE=$SANDBOXP_DIR/logs/build.log
rm -f $LOGFILE
_printLog "Starting $SCRIPTS_DIR/$SCRIPT_NAME AT $(date)"
_printLog ""
_printLog  cd $SANDBOXP_DIR/build
           cd $SANDBOXP_DIR/build
_doLog cmake -DCMAKE_INSTALL_PREFIX:PATH="$INSTALL_DIR_SANDBOXP" $SANDBOXP_DIR
_doLog make
_doLog make install
_printLog
_printLog "Finished $SCRIPTS_DIR/$SCRIPT_NAME AT $(date)"
_printLog
_printLog "Build log in $LOGFILE"
