#!/bin/bash

SCRIPT_NAME=$(basename "$0")
SCRIPTS_DIR=$(pwd)
cd $(dirname "$0")
SCRIPTS_DIR=$(pwd)
cd ../
SANDBOXP_DIR=$(pwd)
INSTALL_DIR_SANDBOXP=$SANDBOXP_DIR/install
cd ${INSTALL_DIR_SANDBOXP}/bin
echo "pwd: $(pwd)"
./sandboxp
